Don't detach, build needs to complete
fabric8-services/fabric8-devdoc pull request #121
Opened 2016-12-10 01:02 UTC by pmuir

2016-12-10 01:16 UTC, pmuir commented
[test]

2016-12-13 10:26 UTC, kwk requested changes

2016-12-13 10:26 UTC, kwk commented on cico_run_tests.sh
> +docker run --name=almighty-devdoc-builder -t -v $(pwd):/almighty-devdoc:Z almighty-devdoc-builder "jekyll build"
I think we can drop the name as well if we don't detach the container.

2018-08-31 18:11 UTC, alexeykazakov commented
Closing as outdated.

2018-08-31 18:11 UTC, closed without merging