WIP: Simplify usage of devdoc via docker
fabric8-services/fabric8-devdoc pull request #84
Opened 2016-10-14 15:57 UTC by maxandersen

Why:

 * Not all OS have easy to install instructions for jekyll
   and the dependencies. Making it hard to use for casual developers.

This change addreses the need by:

 * Make a Dockerfile that is automatically built and let you run
   a simple docker command to do the serving of the result.
 * Adds ruby version to gemfile for reliable use of rvm
 * Add dockerfile in root together with dockerignore to have
   the dockerfile not include the actual repo, but just the gem setup.
 * Enable hawkins plugin to allow for use of livereload

2016-10-14 15:59 UTC, maxandersen commented
one thing I don't Know what to do with is our existing dockerfile that seem to require and do much more than necessary to build.

@kwk any ideas why we need those different permission changes and both build and source volume mounts ?

2016-11-08 07:04 UTC, kwk requested changes

2016-11-08 07:04 UTC, kwk commented on cico_run_tests.sh
> +docker run --detach=true --name=almighty-devdoc-builder -t -v $(pwd):/almighty-devdoc:Z almighty-devdoc-builder "jekyll build"
Would be nice to run the container with `-u` so that mounted artifacts can be deleted by the user who ran the container.

2016-11-12 00:08 UTC, maxandersen commented
this was merged in by other means.

2016-11-12 00:08 UTC, closed without merging